---
version: "2.0"
services:
  oline-forward-left-node:
    image: ${OMNIBUS_IMAGE}
    expose:
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 26657
        as: 26657
        to:
          - global: true
    env:
      - MONIKER=terp-node
      # default chain cfg
      - CHAIN_JSON=${CHAIN_JSON}
      - MINIMUM_GAS_PRICES=0.05uthiol
      # use our seed & snapshot
      - TERPD_P2P_SEEDS=${TERPD_P2P_SEEDS}
      # - SNAPSHOT_URL=https://snapshots.nodejumper.io/terp/terp_latest.tar.lz4
      - FASTSYNC_VERSION=v0
      - STATESYNC_SNAPSHOT_INTERVAL=500
      - STATESYNC_RPC_SERVERS=<https://statesync-a.terp.network:443,https://statesync-b.terp.network:443>
      - ADDRBOOK_URL=${ADDRBOOK_URL}
      # default pruning
      - PRUNING=default
      # enable peer exchange
      - TERPD_P2P_PEX=true
      # left & right tackles are private & unconditional peers
      - TERPD_P2P_PRIVATE_PEER_IDS=${TERPD_P2P_PRIVATE_PEER_IDS}
      - TERPD_P2P_UNCONDITIONAL_PEER_IDS=${TERPD_P2P_UNCONDITIONAL_PEER_IDS}
      # our snapshot as persistent peer
      - TERPD_P2P_PERSISTENT_PEERS=${TERPD_P2P_PERSISTENT_PEERS}
  oline-forward-right-node:
    image: ${OMNIBUS_IMAGE}
    expose:
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 26657
        as: 26657
        to:
          - global: true
    env:
      - MONIKER=terp-node
      # default chain cfg
      - CHAIN_JSON=${CHAIN_JSON}
      - MINIMUM_GAS_PRICES=0.05uthiol
      # use our seed & snapshot
      - FASTSYNC_VERSION=v0
      - STATESYNC_SNAPSHOT_INTERVAL=500
      - STATESYNC_RPC_SERVERS=<https://statesync-a.terp.network:443,https://statesync-b.terp.network:443>
      - ADDRBOOK_URL=${ADDRBOOK_URL}
      - TERPD_P2P_SEEDS=${TERPD_P2P_SEEDS}
      # - SNAPSHOT_URL=https://snapshots.nodejumper.io/terp/terp_latest.tar.lz4
      # default pruning
      - PRUNING=default
      # enable peer exchange
      - TERPD_P2P_PEX=true
      # left & right tackles are private & unconditional peers
      - TERPD_P2P_PRIVATE_PEER_IDS=${TERPD_P2P_PRIVATE_PEER_IDS}
      - TERPD_P2P_UNCONDITIONAL_PEER_IDS=${TERPD_P2P_UNCONDITIONAL_PEER_IDS}
      # our snapshot as persistent peer
      - TERPD_P2P_PERSISTENT_PEERS=${TERPD_P2P_PERSISTENT_PEERS}
profiles:
  compute:
    oline-forward-left-node:
      resources:
        cpu:
          units: 4
        memory:
          size: 16Gi
        storage:
          - size: 60Gi
    oline-forward-right-node:
      resources:
        cpu:
          units: 4
        memory:
          size: 16Gi
        storage:
          - size: 60Gi
  placement:
    dcloud:
      pricing:
        oline-forward-left-node:
          denom: uakt
          amount: 1000
        oline-forward-right-node:
          denom: uakt
          amount: 1000
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      attributes:
        host: akash
deployment:
  oline-forward-left-node:
    dcloud:
      profile: oline-forward-left-node
      count: 1
  oline-forward-right-node:
    dcloud:
      profile: oline-forward-right-node
      count: 1
