version: '3.4'

services:
  node_1:
    build:
      context: ../
      args:
        PROJECT: terpnetwork
        PROJECT_BIN: terpd
        VERSION: v4.2.2
        REPOSITORY: https://github.com/terpnetwork/terp-core
        NAMESPACE: TERPD
        PROJECT_DIR: .terp
    ports:
      - '26656:26656'
      - '26657:26657'
      - '1317:1317'
    environment:
      - MONIKER=node_1
      - CHAIN_ID=morocco-1
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/terpnetwork/chain.json
      - GENESIS_URL=https://raw.githubusercontent.com/terpnetwork/networks/main/mainnet/morocco-1/genesis.json
      - P2P_PERSISTENT_PEERS=a81dc3bf1bb1c3837b768eeb82659eecc971890b@terp-mainnet-peer.itrocket.net:13656
      - P2P_SEEDS=d8256642afae77264bcce1631d51233a9d00249b@terp-mainnet-seed.itrocket.net:13656
    # - SNAPSHOT_WASM_PATH=wasm
    # env_file:
    #   - ../.env
    volumes:
      - ./node-data:/root/.terp
